# Generated by Django 4.2.20 on 2025-03-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical', to='shop.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
